[package]
name = "Sulmo"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = {version="0.26.*"}
serde = {version="1.0.*", features=["derive"]}
serde_json = {version="1.0.*"}
ratatui = {version="0.22.*", features=["all-widgets"]}
tui-input = {version="0.7.*"}